---
title: "Project Script"
output:
  html_document:
    highlight: null
    theme: united
---

This the script of my analysis.

```{r, echo=FALSE, message=FALSE}
rm(list=ls())
library("ggplot2")
library("ggmap")
library("mapdata")
library("lubridate")
library("plyr") #always put before following
library("dplyr")
```

1.CLEANING
--------------
## 1. Ship positions

I combine 6 data sets to get a simple dataframe : position. Details below.

```{r}
##### Loading
shipPos<-list()
i<-1
fileExtension<-c("A", "E", "O","S","Y","I")

load3<-function(file) {
  tempFile<-read.table(file, sep="\t", quote="",fill=T, header=T, stringsAsFactors=F)
  tempFile<-tempFile[-which(tempFile$position==""),-c(4,5)]
  return(tempFile)
}

for (letter in fileExtension) {
  myfile<-paste0("ship",letter)
  myzip<-paste0("../",myfile,".zip")
  mytxt<-paste0(myfile,".txt")
  shipPos[[i]]<-load3(unz(myzip, mytxt))
  i<-i+1
}
AA<-do.call(rbind, shipPos)
AA2<-unique(AA) # a data frame of 184 000 unique positions

#### Cleaning : transform latitude and longitude into numbers and decimal degree units

latlg<-do.call(rbind,strsplit(AA2$position, ", "))

f<-function(x) gsub("'","",x)
latlg2<-apply(latlg,c(1,2),FUN=f) 

f2<-function(x) strsplit(x,"[ \\°]")
library("plyr")
lat<-ldply(sapply(latlg2[,1],FUN=f2))
lg<-ldply(sapply(latlg2[,2],FUN=f2))
lat<-lat[,-1]
lg<-lg[,-1]

convert<-function(x) {
  y<-as.numeric(x[,2])+as.numeric(x[,3])/60
  y<-ifelse ((x[,1]=="S")|(x[,1]=="W"), -y,y)
}

L<-convert(lat)
LL<-convert(lg)
position<-data.frame("lat"=L,"long"=LL)

str(position)

head(position,3)

tail(position,3)
```

## 2. Casualties

I started with 6 reports in pdf. I converted them in txt with okular. The transformation from txt to csv was done in python,
I then combined and further clean the 6 datasets in csv in R.

  * txt to csv

In the txt format, the data concerning 1 accident are given on 3 rows with different fixed width format. I reshaped it on 1 row in the csv format.
I select only the accidents were the position is given ( with latitude and longitude).

```
This is the code in python for one document, the code had to be tuned to each document

import re
import os
import csv
try:
    from itertools import izip_longest  # added in Py 2.6
except ImportError:
    from itertools import zip_longest as izip_longest  # name change in Py 3.x
try:
    from itertools import accumulate  # added in Py 3.2
except ImportError:
    def accumulate(iterable):
        'Return running totals (simplified version).'
        total = next(iterable)
        yield total
        for value in iterable:
            total += value
            yield total

##### LOGISTIC
os.chdir('/home/anne/projet IDTA')

filename = 'casualty2000.txt'

new_file = []

pattern1  = '^([A-Z]+[a-z]*){2,6}|Other' #identify the first line
pattern4 = "[0-9]+o*[0-9]*\'*[\\.]*[0-9]*[A-Z]" #latitude and longitude pattern

with open(filename, 'r') as f:
   lines = f.readlines()

##### FUN DEF
def make_parser(fieldwidths):
    cuts = tuple(cut for cut in accumulate(abs(fw) for fw in fieldwidths))
    pads = tuple(fw < 0 for fw in fieldwidths) # bool values for padding fields
    flds = tuple(izip_longest(pads, (0,)+cuts, cuts))[:-1]  # ignore final one
    parse = lambda line: tuple(line[i:j] for pad, i, j in flds if not pad)
    # optional informational function attributes
    parse.size = sum(abs(fw) for fw in fieldwidths)
    parse.fmtstring = ' '.join('{}{}'.format(abs(fw), 'x' if fw < 0 else 's')
                                                for fw in fieldwidths)
    return parse

def parse_line(line,*args):  #parse the first line
    parse = make_parser(args)
    return parse(line)

def parse_l23(line):         #parse the 2nd and 3rd line
    if len(line)<190 :
        fields = (-7, 60, 8,-9,(len(line)-153),40) #143
    else :
        fields = (-7, 60, 8,-10,(len(line)-163),40)
    fieldsL2 = parse_line(line,*fields)
    return fieldsL2

# Iterate each line
for i in xrange(len(lines)):

    # Regex applied to each line 
    match = re.search(pattern1, lines[i]) # je cherche la classe
    if match:
        latLong=re.findall(pattern4, lines[i]) # je cherche s'il y a la position
        if len(latLong)>1:
            if len(lines[i])<190 :
                fields = (-7, 60, 8,10,(len(lines[i])-155),27,27,10,10)##143
            else :
                fields = (-7, 60, 8,11,(len(lines[i])-163),27,27,15,15)
            fieldsL1 = parse_line(lines[i],*fields)    
            fieldsL1 = (match.group(),)+fieldsL1
            
            fieldsL2 = parse_l23(lines[i+1])
            
            fieldsL3 = parse_l23(lines[i+2])
            
            new_line=map(lambda x: x.strip(), list(fieldsL1+fieldsL2+fieldsL3))
            new_file.append(new_line)

#export
with open('casualty2000clean.csv', 'w') as f:
     # go to start of file
     f.seek(0)
     writer=csv.writer(f)
     # actually write the lines
     writer.writerows(new_file)
```

  * csv loading and cleaning

My final output is the dataframe casualty, detailed below.

```{r, message=FALSE}
shipAcc<-list()
i<-1

fileExtension<-c("1998", "1999", "2000","2001","2002","2003")
cC<-c(NA, "character","NULL",rep("character",6),rep("NULL",2), "character", "NULL", 
      "character", "numeric", "character", "NULL")

for (letter in fileExtension) {
  myfile<-paste0("../casualty",letter,"clean.csv")
  shipAcc[[i]]<-read.csv(myfile, stringsAsFactors=F, colClasses=cC, header=F)
  i<-i+1
}
casualty<-do.call(rbind, shipAcc)
names(casualty)<-c("dataSource", "flagState", "date", "casLife",
                   "lat", "long", "fatalities", "injuries", "consequence", "shipType", "DOB", "category")

#### Cleaning, in feature order

#dataSource: source of data. nothing to do

#flagState: flag State
cleanflag<-function(x) {
  x<-toupper(x)
  x[grepl("^CHINA", x)]<-"CHINA"
  x[grepl("^MARSHALL", x)]<-"MARSHALL ISLANDS"
  x<-gsub("KINGDON","KINGDOM",x)
  x<-gsub("S REP$"," REPUBLIC OF",x)
  x<-gsub(" BARGUDA", " BARBUDA",x)
  x<-gsub("VIET NAM","VIETNAM", x)
  x<-gsub("&","AND", x)
  x<-gsub("NETHERLANDS,","NETHERLANDS", x)
  return(x)
}

casualty$flagState<-cleanflag(casualty$flagState)


#date
library(lubridate)
dateclean<-function(x) {
  temp<-dmy(x)
  f3<-function(x) ifelse(x<2000, x+1900, x)
  year(temp)<-sapply(year(temp),f3)
  return(temp)
}
casualty$date<-dateclean(casualty$date)


#casLife (was someone injured or killed)
temp1<-gsub(" \\(.*\\)","",casualty$casLife)
temp1<-gsub("Casualty","Serious casualty", temp1)

casualty$casLife<-as.factor(temp1)


#lat and long: latitude and longitude
fmin<-function(x, pattern) {
  y<-ifelse(grepl(pattern,x),regmatches(x,regexec(pattern,x)), "0")
}
library(plyr)

convert2<-function(x) {
  l1<-do.call(rbind,strsplit(x,"o"))
  l2<-ldply(sapply(l1[,2], fmin, "^[0-9]+"))[,2] #I need only the values, not any name
  l3<-ldply(sapply(l1[,2], fmin, "\\.[0-9]+"))[,2]
  l4<-ldply(sapply(l1[,2], fmin, "[A-Z]"))[,2]
  l5<-as.numeric(l1[,1])+as.numeric(l2)/60+as.numeric(l3)
  l5<-ifelse ((l4=="S")|(l4=="W"), -l5,l5)
  return(l5)
}

casualty$lat<-convert2(casualty$lat)
casualty$long<-convert2(casualty$long)


#fatalities and injuries
casualty$fatalities<-as.numeric(casualty$fatalities) #warnings for missing data
casualty$injuries<-as.numeric(casualty$injuries)  #warnings for missing data


#consequence : a consequence of the accident

cleantype<-function(x) {
  bkdnwithshore<-grepl("^B(.*)", x) & !grepl("^B(.*)g", x)
  x[bkdnwithshore]<-"Breakdown with shore assistance"
  x[grepl("^C(.*)", x)]<-"Constructive total loss"
  x<-gsub(" \\(.*\\)","",x)
  x[grepl("[Hh]ull", x)]<-"Structural damage"
  x[grepl("Tot(.*)lif(.*)*",x)]<-"Total loss and loss of life"
   x[grepl("Tot(.*)shi(.*)*",x)]<-"Total loss"
  return(x)
}

casualty$consequence<-cleantype(casualty$consequence)

#shipType: type of ship

cleanship<-function(x) {
  x<-toupper(x)
  x[grepl("BA(.*)",x)]<-"BARGE"
  x[grepl("BULK",x)]<-"BULK CARRIER"
  x[grepl("FISH",x)]<-"FISH RELATED SHIP"
  x[grepl("GAS ",x)]<-"GAS CARRIER"
  x[grepl("ICE(.*) ",x)]<-"ICEBREAKER"
  x[grepl("^RO(.*)",x)]<-"RO-RO CARGO SHIP"
  x[grepl("^TA(.*) ",x)]<-"TANKER"
  x[grepl("TUG",x)]<-"TUG"
  x[grepl("^VEH(.*)",x)]<-"VEHICLES CARRIER"
  return(x)
}

casualty$shipType<-cleanship(casualty$shipType)

#DOB: year of construction, nothing


#category: category of the accident

cleancat<-function(x){
  x[grepl("^Cap(.*)",x)]<-"Capsize"
  x[grepl("Fail(.*)",x)]<-"Hull failure"
  x[grepl("Fire and explosion",x)]<-"Fire/Explosion"
  grounding<-grepl("Groun(.*)",x) | grepl("Stra(.*)",x)
  x[grounding]<-"Grounding"
  x[grepl("Other(/|$)",x)]<-"Unknown"
  x[grepl("Work",x)]<-"Work-related accident"
  x[grepl("Fall",x)]<-"Fall overboard"
  return(x)
}

casualty$category<-cleancat(casualty$category)

str(casualty)

head(casualty,3)
tail(casualty,3)
```

2. GEOGRAPHICAL ANALYSIS
-------------------------

World map
``` {r}
world_map <- borders("worldHires", colour="#99FF99" ,fill="#99FF99") # create a layer of borders
mp <- ggplot(position, aes(x=long, y=lat)) + world_map 
mp<-mp + stat_density2d(aes(fill = ..level..), geom="polygon") + 
  scale_fill_gradient(low="#9999CC", high="#663399",name ="ship density") +
  geom_point(data= casualty, aes(x=long, y=lat, color=as.factor(casLife)), size=1) +
  scale_color_manual(values=c("#FF9900","#330000")) + 
  labs( x="longitude", y="latitude", color="casualty")
mp
range(position$lat)
range(position$long)
```

Europe map
```{r}
fzone<-function(df,lat1,lat2,long1,long2=-long1) {
  cond<-with(df,(lat>lat1 & lat <lat2)&(long>long1 & long<long2))
  df2<-df[with(df,cond),]
  return(df2)
}
eur_pos<-fzone(position,47,58,-15,15)
eur_cas<-fzone(casualty,47,58,-15,15)

mp_eur <- ggplot(eur_pos, aes(x=long, y=lat)) + world_map + coord_cartesian(
  xlim=c(-15,15),ylim=c(47,58)) 
mp_eur + geom_point(color="#9999CC",size=1.7) + 
  geom_point(data= eur_cas, aes(x=long, y=lat, color=as.factor(casLife)), size=1.3) +
  scale_color_manual(values=c("#FF9900","#330000")) + 
  labs( x="longitude", y="latitude", color="casualty")
```

China sea
```{r}
asi_cas<-fzone(casualty,17,38,110,139)

nrow(eur_cas)
nrow(asi_cas)
round(2014-mean(eur_cas$DOB[eur_cas$DOB>=1850 & eur_cas$DOB<=2020], na.rm=T))
round(2014-mean(asi_cas$DOB[asi_cas$DOB>=1850 & asi_cas$DOB<=2020], na.rm=T))

ggplot()+ 
  scale_fill_manual(values=c("#FF000033","#0000FF33"), name="Area",labels=c("China Coast","Europe")) +
  geom_bar(data=eur_cas, aes(x=consequence, fill="Europe"),stat="bin") + #pour destack ,position="dodge"
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x="type of casualty") +
  geom_bar(data=asi_cas,aes(x=consequence, fill="China Coast"),stat="bin")
```

Heatmap
```{r}
position$latCut<-cut(position$lat,breaks = seq(-90,90,length.out=11))
position$longCut<-cut(position$long,breaks = seq(-180,180,length.out=21))
poscut<-position%.%group_by(latCut, longCut)%.%summarise(position=n())

casualty$latCut<-cut(casualty$lat,breaks = seq(-90,90,length.out=11))
casualty$longCut<-cut(casualty$long,breaks = seq(-180,180,length.out=21))
cascut<-casualty%.%group_by(latCut, longCut)%.%summarise(casualty=n())

heat<-merge(poscut,cascut)
heat$density<-heat$casualty/heat$position

ggplot(data=heat, aes(x=longCut, y=latCut, fill=density))+geom_tile() +
  scale_fill_gradient(low="#9999CC", high="#663399",name ="density") +
  labs(x="longitudinal cuts", y="latitude cuts", title="Casualties Heatmap")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

Africa corn
```{r}
rs_cas<-casualty[casualty$latCut=="(0,18]" & casualty$longCut=="(36,54]",]
rs_cas%.%group_by(consequence)%.%summarise(count=n())%.%arrange(desc(count))
```

3. Casualty Factors
-------------------

casLife : did the accident involve injuries or fatalities.
```{r}
ser.table<-table(casualty$casLife)
ser.df<-data.frame(ser.table,"Percentage"=round(ser.table/sum(ser.table)*100,2))[,-3]
names(ser.df)<-c("seriousness","count","percentage")
ser.df
```

flagState
```{r}
length(unique(casualty$flagState)) #number of countries
flag.table<-sort(table(casualty$flagState), decreasing=T) # number of accidents per country
flag.freq<-data.frame("casualtyPercentage"=round(flag.table/sum(flag.table)*100,2)) # frequency
head(flag.freq,3)

#CIA data
cia.ship<-read.table("../ciaship.txt", sep="\t", stringsAsFactors=F)
cia.ship<-cia.ship[,-1]
names(cia.ship)<-c("flagState", "merchantMarine")
cia.ship$flagState<-toupper(cia.ship$flagState)
cia.ship$merchantMarine<-as.numeric(gsub(",","",cia.ship$merchantMarine))
cia.ship$fleetPercentage<-round(cia.ship$merchantMarine/sum(cia.ship$merchantMarine)*100,2)
length(unique(cia.ship$flagState))
head(cia.ship[,c(1,3)],3)
```

date
```{r}
casualty%.%group_by("year"=year(date))%.%summarise(nb=n())
```

fatalities and injuries
```{r}
# fatalities and injuries by year
casualty%.%group_by("year"=year(date))%.%summarise(nbFatlities=sum(fatalities, na.rm=T),
                                                   nbInjured=sum(injuries, na.rm=T))

#fatalities by year and number of accidents involving fatalities
casualty[casualty$fatalities>0 &!is.na(casualty$fatalities),]%.%group_by("year"=year(
  date))%.%summarise(nb=n(),nbFatlities=sum(fatalities))

#worst casualty
casualty[which.max(casualty$fatalities),2:12]
```

shipType
```{r}
#number and frequency of accidents pe ship type
ship.table<-sort(table(casualty$shipType), decreasing=T) 
ship.freq<-data.frame("casualtyPercentage"=round(ship.table/sum(ship.table)*100,2))
head(ship.freq,3)

#Equasis data
world.fleet<-read.table("../worldfleet2005.txt", sep=";",stringsAsFactors=F, header=T,colClasses=
                          c("character","numeric","NULL"))
world.fleet$percentage<-round(world.fleet$Total/sum(world.fleet$Total)*100,2)
head(world.fleet[order(world.fleet$percentage, decreasing=T),c(1,3)],3)

#most dangerous ships
#general cargo ship
head(casualty[casualty$shipType=="GENERAL CARGO SHIP",]%.%group_by(category)%.%summarise(
  count=n())%.%arrange(desc(count)),3)
head(casualty[casualty$shipType=="GENERAL CARGO SHIP",]%.%group_by(consequence=consequence)%.%summarise(
  count=n())%.%arrange(desc(count)),3)
casualty[casualty$shipType=="GENERAL CARGO SHIP",]%.%group_by(casLife)%.%summarise(
  count=n())
#match with non general cargo ships
head(casualty[casualty$shipType!="GENERAL CARGO SHIP",]%.%group_by(category)%.%summarise(
  count=n())%.%arrange(desc(count)),3)
head(casualty[casualty$shipType!="GENERAL CARGO SHIP",]%.%group_by(consequence)%.%summarise(
  count=n())%.%arrange(desc(count)),3)
casualty[casualty$shipType!="GENERAL CARGO SHIP",]%.%group_by(casLife)%.%summarise(
  count=n())

#tugs
head(casualty[casualty$shipType=="TUG",]%.%group_by(category)%.%summarise(
  count=n())%.%arrange(desc(count)),3)
head(casualty[casualty$shipType=="TUG",]%.%group_by(consequence)%.%summarise(
  count=n())%.%arrange(desc(count)),3)
casualty[casualty$shipType=="TUG",]%.%group_by(casLife)%.%summarise(
  count=n())

#ro-ro cargo ships. ro-ro stands for roll on roll of, trucks can enter and get out of the ship directly.
head(casualty[casualty$shipType=="RO-RO CARGO SHIP",]%.%group_by(category)%.%summarise(
  count=n())%.%arrange(desc(count)),3)
head(casualty[casualty$shipType=="RO-RO CARGO SHIP",]%.%group_by(consequence=consequence)%.%summarise(
  count=n())%.%arrange(desc(count)),3)
casualty[casualty$shipType=="RO-RO CARGO SHIP",]%.%group_by(casLife)%.%summarise(
  count=n())
```

DOB ship year of construction
```{r}
summary(casualty$DOB[casualty$DOB>=1800 & casualty$DOB<2010])
```

consequence and category
```{r}
summary(table(casualty$consequence, casualty$category))$statistic #chi square
summary(table(casualty$consequence, casualty$category))$p.value   

ggplot(casualty, aes(x=casLife, fill=category))+geom_bar(stat="bin") + 
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      strip.text.x = element_text(angle = 90)) +
labs(x="seriousness of accident", fill="category") +
facet_grid(.~consequence, scales="free", space="free")
```
